<?php

if (function_exists('xdebug_disable'))
    xdebug_disable();

require('../../src/SettingsManager/settingsmanager.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-08 at 17:48:59.
 */
class settingsManagerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var settingsManager
     */
    protected $object;
    
    private $_testData = array(
        'data' => 1,
        'data2' => array(
            'date3' => 4
            )        
    );

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
       $this->object = new SettingsManager\settingsManager($this->_testData);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SettingsManager\settingsManager::get
     * 
     */
    public function testGet()
    {
        $this->assertTrue($this->object->get('data2/date3') == 4);       
    }
    
    /**
     * @expectedException \OutOfBoundsException 
     */
    public function testGetFail() {
        $this->assertTrue($this->object->get('fail') == 4);
    }

    /**
     * @covers SettingsManager\settingsManager::set
     * @todo   Implement testSet().
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SettingsManager\settingsManager::exists
     * @todo   Implement testExists().
     */
    public function testExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SettingsManager\settingsManager::cacheGet
     * @todo   Implement testCacheGet().
     */
    public function testCacheGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SettingsManager\settingsManager::cacheSet
     * @todo   Implement testCacheSet().
     */
    public function testCacheSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SettingsManager\settingsManager::clearCache
     * @todo   Implement testClearCache().
     */
    public function testClearCache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
